<?php
/**
 * @file
 * Code for the Open Atrium Recent Activity feature.
 */

include_once 'oa_river.features.inc';

/**
 * Implements hook_theme()
 */
function oa_river_theme() {
  return array(
    'views_view_fields__oa_recent_activity__panel_pane' => array(
      'template'  => 'views-view-fields--oa-recent-activity--panel-pane',
      'base hook' => 'views_view_fields',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view_fields',
        'oa_groups_preprocess_views_view_fields',
      ),
      'arguments' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
      'path' => drupal_get_path('module', 'oa_river') . '/templates',
    ),
  );
}
