<?php

/**
 * Implements hook_block_info()
 */
function oa_dashboard_block_info() {
  $blocks['oa_toolbar'] = array(
    'info' => t('Open Atrium Toolbar'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function oa_dashboard_block_view($delta = '') {
  $block = array();

  switch($delta) {
  	case 'oa_toolbar':
  	  $block['subject'] = t('Open Atrium Toolbar');
      $block['content'] = theme('oa_toolbar');
  	  break;
  }

  return $block;
}

/**
 * Implements hook_theme()
 */
function oa_dashboard_theme() {
  return array(
    'oa_toolbar' => array(
      'template' => 'oa_toolbar',
    ),
  );
}

function oa_dashboard_preprocess_oa_toolbar(&$variables) {
  // Separators
  $variables['oa_toolbar_separator'] = t('&gt;');
  $variables['home_url'] = url('<front>', array('absolute' => TRUE));

  // Groups
  if (isset($_SESSION['oa_group_id'])) {
    $group = node_load($_SESSION['oa_group_id']);
  }
  $group_options = array(
                      'attributes' => array(
                        'class' => array('dropdown-toggle', 'btn', 'btn-large', 'btn-success'),
                        )
                      );
  $variables['groups_label'] = l(t('Groups'), '<front>', $group_options);
  $variables['sections_main'] = '';
  if (isset($group) && $group->type === 'oa_group') {
    $variables['groups_label'] = l($group->title, 'node/' . $group->nid, $group_options);
    $variables['sections_main'] = l(t('Group page'), 'node/' . $group->nid);
  }

  $variables['groups_recent'] = views_embed_view('open_atrium_groups', 'groups');

  // Sections
  $section = menu_get_object();

  $variables['sections_label'] = t('Main');
  if (isset($section->type) && ($section->type == OA_SECTION_TYPE)) {
    $variables['sections_label'] = $section->title;
  }

  $variables['sections_list'] = views_embed_view('open_atrium_section_pages', 'section_pages_within_groups');
}


function oa_dashboard_preprocess_views_view(&$variables) {
  if ($variables['display_id'] === 'section_pages_within_groups') {
  }
}
