<?php

/**
 * Implements hook_block_info()
 */
function oa_dashboard_block_info() {
  $blocks['oa_toolbar'] = array(
    'info' => t('Open Atrium Toolbar'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function oa_dashboard_block_view($delta = '') {
  $block = array();

  switch($delta) {
  	case 'oa_toolbar':
  	  $block['subject'] = t('Open Atrium Toolbar');
      $block['content'] = theme('oa_toolbar');
  	  break;
  }

  return $block;
}

/**
 * Implements hook_theme()
 */
function oa_dashboard_theme() {
  return array(
    'oa_toolbar' => array(
      'template' => 'oa_toolbar',
    ),
  );
}

function oa_dashboard_preprocess_oa_toolbar(&$variables) {
  global $user;

  // Separators
  $variables['oa_toolbar_separator'] = t('&gt;');
  $variables['home_url'] = url('<front>', array('absolute' => TRUE));

  // Groups
  if (isset($_SESSION['oa_group_id'])) {
    $group = node_load($_SESSION['oa_group_id']);
  }
  $group_options = array(
                      'attributes' => array(
                        'class' => array('dropdown-toggle', 'btn', 'btn-large', 'btn-success'),
                        )
                      );
  $variables['groups_label'] = l(t('Groups'), '<front>', $group_options);
  $variables['sections_main'] = '';
  if (isset($group->type) && ($group->type == 'oa_group')) {
    $variables['groups_label'] = l($group->title, 'node/' . $group->nid, $group_options);
    $variables['sections_main'] = l(t('Group page'), 'node/' . $group->nid);
  }

  // grab list of user's groups and sections
  $sections = oa_groups_section_list($user->uid);

  // get names of groups
  $query = db_select('node', 'n');
  $query
    ->fields('n', array('nid', 'title'))
    ->condition('n.type', 'oa_group')
    ->condition('n.nid', array_keys($sections), 'IN');
  $result = $query->execute();
  $items = array();
  while ($row = $result->fetchAssoc()) {
    $items[] = l($row['title'], 'node/' . $row['nid']);
  }

  $variables['groups_recent'] = theme('item_list', array(
    'items' => $items,
    'title' => t('Active Groups'),
    'type' => 'ul'));

  $variables['groups_favorite'] = '';
  if (module_exists('oa_favorites')) {
    if ($flag = flag_get_flag('favorite_group')) {
      $query = db_select('node', 'n');
      $query->join('flag_content', 'f', 'n.nid = f.content_id');
      $query
        ->fields('n', array('nid', 'title'))
        ->condition('f.uid', $user->uid);
      $result = $query->execute();
      $items = array();
      while ($row = $result->fetchAssoc()) {
        $items[] = l($row['title'], 'node/' . $row['nid']);
      }
      if (!empty($items)) {
        $variables['groups_favorite'] = theme('item_list', array(
          'items' => $items,
          'title' => t('Favorite Groups'),
          'type' => 'ul'));
      }
    }
  }

  $variables['sections_label'] = t('Group page');
  $items = array();
  $variables['sections_list'] = '';
  if (isset($group->nid)) {
    $items[] = l(t('Group page'), 'node/' . $group->nid);
    if (!empty($sections[$group->nid])) {
      // get names of sections
      $query = db_select('node', 'n');
      $query
        ->fields('n', array('nid', 'title'))
        ->condition('n.nid', $sections[$group->nid], 'IN');
      $result = $query->execute();
      while ($row = $result->fetchAssoc()) {
        $items[] = l($row['title'], 'node/' . $row['nid']);
      }
    }
  }
  if (!empty($items)) {
    $variables['sections_list'] = theme('item_list', array(
      'items' => $items,
      'type' => 'ul'));
  }

  // Current Section Name
  $section = menu_get_object();
  if (isset($section->type) && ($section->type == OA_SECTION_TYPE)) {
    $variables['sections_label'] = $section->title;
  }
}

function oa_dashboard_preprocess_views_view(&$variables) {
  if ($variables['display_id'] === 'section_pages_within_groups') {
  }
}
