<?php

/**
 * Implements hook_block_info()
 */
function oa_dashboard_block_info() {
  $blocks['oa_toolbar'] = array(
    'info' => t('Open Atrium Toolbar'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function oa_dashboard_block_view($delta = '') {
  $block = array();

  switch($delta) {
  	case 'oa_toolbar':
  	  $block['subject'] = '';
      $block['content'] = theme('oa_toolbar');
  	  break;
  }

  return $block;
}

/**
 * Implements hook_theme()
 */
function oa_dashboard_theme() {
  return array(
    'oa_toolbar' => array(
      'template' => 'oa_toolbar',
    ),
  );
}

function oa_dashboard_preprocess_oa_toolbar(&$variables) {
  global $user;

  // Separators
  $variables['oa_toolbar_separator'] = t('&gt;');
  $variables['home_url'] = url('<front>', array('absolute' => TRUE));

  // Groups
  $group_id = NULL;
  if (isset($_SESSION['oa_group_id'])) {
    $group_id = $_SESSION['oa_group_id'];
  }
  $variables['groups_label'] = '';
  $variables['groups_recent'] = '';
  $variables['groups_favorite'] = '';
  $variables['sections_label'] = '';
  $variables['sections_list'] = '';

  // grab list of user's groups and sections
  $sections = oa_groups_section_list($user->uid);
  if (!empty($sections)) {
    $group_options = array(
      'attributes' => array(
        'class' => array('dropdown-toggle', 'btn', 'btn-large', 'btn-success'),
        )
      );
    $variables['groups_label'] = l(t('Groups'), 'groups', $group_options);
    if (isset($group_id)) {
      // get name of current group (without fully loading node)
      $title = oa_groups_get_titles(array($group_id));
      $variables['groups_label'] = l($title['titles'][0], 'node/' . $group_id, $group_options);
    }

    // get names of groups
    $items = oa_groups_get_titles(array_keys($sections), OA_GROUP_TYPE);
    $list = oa_groups_truncate_list($items['links'], 10,
      l('All groups...', 'groups',
        array('attributes' => array('class' => array('more-link')))));
    if (!empty($list)) {
      $variables['groups_recent'] = theme('item_list', array(
        'items' => $list,
        'title' => t('Active Groups'),
        'type' => 'ul',
      ));
    }

    if (module_exists('oa_favorites')) {
      // get list of favorite groups
      $items = oa_favorites_get_groups($user);
      if (!empty($items['links'])) {
        $variables['groups_favorite'] = theme('item_list', array(
          'items' => $items['links'],
          'title' => t('Favorite Groups'),
          'type' => 'ul',
        ));
      }
    }

    $current_section = !empty($_SESSION['oa_section_id']) ? $_SESSION['oa_section_id'] : 0;
    $section_name = '';

    $variables['sections_label'] = t('Group home');
    if (isset($group_id)) {
      $group_link = l(t('Group home'), 'node/' . $group_id);
      // grab the titles of the sections for the current group
      if (isset($sections[$group_id])) {
        $items = oa_groups_get_titles($sections[$group_id]);
        // check for match with current section id
        for ($i = 0; $i < count($items['ids']); $i++) {
          if ($items['ids'][$i] == $current_section) {
            $section_name = $items['titles'][$i];
            break;
          }
        }
        // add the Group home page link and create the ul list
        array_unshift($items['links'], $group_link);
      }
      else {
        $items['links'][] = $group_link;
      }
      if (!empty($items['links'])) {
        $variables['sections_list'] = theme('item_list', array(
          'items' => $items['links'],
          'type' => 'ul',
        ));
      }
    }

    // Current Section Name from current page name
    $section = menu_get_object();
    if (isset($section->type)) {
      switch ($section->type) {
        case OA_SECTION_TYPE:
          $section_name = $section->title;
          break;
        case OA_GROUP_TYPE:
          $section_name = $variables['sections_label'];
      }
    }
    $variables['sections_label'] = $section_name;
  }
}

function oa_dashboard_preprocess_views_view(&$variables) {
  if ($variables['display_id'] === 'section_pages_within_groups') {
  }
}
