<?php

/**
 * Implements hook_ctools_plugin_directory
 */
function oa_notifications_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_menu().
 */
function oa_notifications_menu() {
  // TODO: What are the proper access conditions here
  $items['js/oa_notifications/details/%node'] = array(
    'title' => 'Open Atrium Notification Details',
    'page callback' => 'oa_notifications_ajax_details',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function oa_notifications_theme() {
  return array(
    'oa_notifications_view' => array(
      'template' => 'oa-notifications-view',
      'variables' => array(
        'node' => NULL,
        'organization' => array(),
        'team' => array(),
        'user' => array(),
      ),
      'path' => drupal_get_path('module', 'oa_notifications') . '/templates',
    ),
    'oa_notifications_details' => array(
      'template' => 'oa-notifications-details',
      'variables' => array(
        'users' => array(),
      ),
      'path' => drupal_get_path('module', 'oa_notifications') . '/templates',
    ),
  );
}

/**
 * Return the resolved list of all users to be notified on a piece of content.
 *
 * @param $node
 *    The node to return notifications
 * @return
 *    An array of users keyed by uid
 */
function oa_notifications_get_notifications($node) {
  $bucket = &drupal_static(__FUNCTION__);

  if (!isset($bucket)) {
    $bucket = array();
    $gid = $_SESSION[OG_SESSION_CONTEXT_ID];
    $notifications = oa_notifications_load_multiple($node->nid);

    if (array_key_exists('organization', $notifications)) {
      foreach (array_keys($notifications['organization']) as $org_id) {
        $users = oa_groups_get_org_users_for_group($gid, $org_id);
        $bucket += $users;
      }
    }

    if (array_key_exists('team', $notifications)) {
      foreach (array_keys($notifications['team']) as $team_id) {
        $results = oa_teams_get_team_members($team_id);
        $users = user_load_multiple(array_keys($results));
        $bucket += $users;
      }
    }

    if (array_key_exists('user', $notifications)) {
      $users = user_load_multiple(array_keys($notifications['user']));
      $bucket += $users;
    }
  }

  return $bucket;
}

/**
 * Some utility functions...
 */

/**
 * Get the listing of user with that are in the specified group, or the current
 * group if no group is specified that also have access to the provided node.
 *
 * @param int $gid
 *    The Group ID
 */
function oa_notifications_get_users_for_node($node, $gid = NULL) {
  if (!isset($gid)) {
    // TODO: Consolidate this in a function
    $gid = $_SESSION[OG_SESSION_CONTEXT_ID];
  }
  $query = db_select('users', 'u');
  $query->rightJoin('og_membership', 'og', 'u.uid = og.etid');
  $query->fields('u', array('uid', 'name'))
      ->condition('og.entity_type', 'user')
      ->condition('og.gid', $gid);

  $results = $query->execute()->fetchAllAssoc('uid');

  // @TODO: This won't scale. We need users that have access to the given node
  // which is controlled by node_access grants, etc.  Not easily queried.
  // The move to an autocomplete might make this potential performance problem disappear.
  $users = user_load_multiple(array_keys($results));
  if (isset($node->nid)) {
    foreach ($users as $uid => $user) {
      if (!node_access('view', $node, $user)) {
        unset($users[$uid]);
      }
    }
  }
  return $users;
}

/**
 * Return all notifications for given source.  Optionally filtered by type.
 *
 * @param int $source_id
 *    The ID of the source (typically a nid)
 * @param string $source_type
 *    The entity type of the source (defaults to 'node')
 * @params string $target_type
 *    An optional parameter that allows to filter the notification based on target type (organization, team, user)
 * @return
 *    Returns an associative array of notifications first keyed by target type,
 *    then beneath that keyed by the target_id
 */
function oa_notifications_load_multiple($source_id, $source_type = 'node', $target_type = NULL) {
  $query = db_select('oa_notifications', 'n')
    ->fields('n')
    ->condition('n.source_id', $source_id)
    ->condition('n.$source_type', $source_type);

  if (isset($target_type)) {
    $query->condition('n.target_type', $target_type);
  }

  $notifications = array();
  $results = $query->execute()->fetchAllAssoc('notification_id');

  foreach ($results as $id => $row) {
    $notifications[$row->target_type][$row->target_id] = $row;
  }

  return $notifications;
}

/**
 * @param $values
 */
function oa_notifications_save_notifications($values) {
  if (isset($values['source_id']) && isset($values['source_type'])) {
    $source_id = $values['source_id'];
    $source_type = $values['source_type'];

    $notifications = array();
    foreach (array('organization', 'team', 'user') as $type) {
      foreach ($values[$type] as $id) {
        $n = new stdClass;
        $n->source_id = $source_id;
        $n->source_type = $source_type;
        $n->target_id = $id;
        $n->target_type = $type;
        $notifications[] = $n;
      }
    }

    oa_notifications_save_for_source($source_id, $source_type, $notifications);
  }
}

/**
 * Save a collection of Notifications for a particular source item.
 *
 * @param int $source_id
 *    The ID of the source (typically a nid)
 * @param string $source_type
 *    The entity type of the source (defaults to 'node')
 * @param array $notifications
 *    A collection of Notification object for this source
 */
function oa_notifications_save_for_source($source_id, $source_type, $notifications) {
  db_delete('oa_notifications')
    ->condition('source_id', $source_id)
    ->condition('source_type', $source_type)
    ->execute();

  foreach ($notifications as $n) {
    drupal_write_record('oa_notifications', $n);
  }
}


/**
 * Implements hook_node_insert().
 */
function oa_notifications_node_insert($node) {
  if (oa_notifications_is_notification_type($node)) {
    $node->oa_notifications['source_id'] = $node->nid;
    oa_notifications_save_notifications($node->oa_notifications);
  }
}

/**
 * Implements hook_node_update().
 */
function oa_notifications_node_update($node) {
  if (oa_notifications_is_notification_type($node) && isset($node->oa_notifications)) {
    oa_notifications_save_notifications($node->oa_notifications);
  }
}

/**
 * Determine if this is an entity type on which we need to provide notifications
 *
 * @param $node
 * @return
 */
function oa_notifications_is_notification_type($node) {
  // @TODO: Implement this as configurable
  // for now, add notifications to any group-content type
  $types = oa_groups_list_content_types(TRUE);
  return (array_key_exists($node->type, $types));
}

/**
 * Implements hook_node_delete().
 *
 * Cleanup the notifications for teams and organizations as they are removed.
 *
 * @param $node
 *    The Node being deleted
 */
function oa_notifications_node_delete($node) {
  if ($node->type == OA_TEAM_TYPE) {
    $target_type = 'team';
  }
  else if ($node->type == OA_ORG_TYPE) {
    $target_type = 'organization';
  }

  if (isset($target_type)) {
    oa_notifications_delete_for_target($node->nid, $target_type);
  }
}

/**
 * Delete notifications for a target
 *
 * @param int $id
 *    The target id (e.g. node id)
 * @param string $type
 *    The target type (e.g. 'organization', 'team')
 */
function oa_notifications_delete_for_target($id, $type) {
  db_delete('oa_notifications')
    ->condition('target_id', $id)
    ->condition('target_type', $type)
    ->execute();
}

/**
 * Callback for AJAX saving of the notification configuration when on a screen with a quick reply.
 *
 * @param $form
 * @param $form_state
 * @return mixed
 */
function oa_notifications_ajax_callback($form, $form_state) {
  oa_notifications_save_notifications($form_state['values']);

  $element = $form_state['triggering_element']['#name'];
  return $form[$element];
}

/**
 * Define the fields that are used for configuring notifications.
 *
 * @param $form
 * @param $form_state
 * @param $node
 */
function oa_notifications_form_fields(&$form, &$form_state, $node) {
  $nid = isset($node->nid) ? $node->nid : NULL;
  $form['source_type'] = array(
    '#type' => 'value',
    '#value' => 'node',
  );
  $form['source_id'] = array(
    '#type' => 'value',
    '#value' => $nid
  );

  $notifications = isset($nid) ? oa_notifications_load_multiple($nid) : array();

  $all_orgs = oa_groups_get_all_orgs();
  $form['organization'] = array(
    '#type' => 'select',
    '#title' => t('Organizations'),
    '#multiple' => TRUE,
    '#options' => array_map(create_function('$org', 'return $org->title;'), $all_orgs),
    '#default_value' => array_key_exists('organization', $notifications) ? array_keys($notifications['organization']) : array(),
  );

  $group_teams = oa_teams_get_teams_for_group();
  $form['team'] = array(
    '#type' => 'select',
    '#title' => t('Teams'),
    '#multiple' => TRUE,
    '#options' => array_map(create_function('$team', 'return $team->title;'), $group_teams),
    '#default_value' => array_key_exists('team', $notifications) ? array_keys($notifications['team']) : array(),
  );

  $group_users = oa_notifications_get_users_for_node($node);
  $form['user'] = array(
    '#type' => 'select',
    '#title' => t('Users'),
    '#multiple' => TRUE,
    '#options' => array_map(create_function('$user', 'return $user->realname;'), $group_users),
    '#default_value' => array_key_exists('user', $notifications) ? array_keys($notifications['user']) : array(),
  );

}

/**
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function oa_notifications_form_node_form_alter(&$form, &$form_state, $form_id) {
  // we are on a node/edit/add form.
  // check content type
  if (isset($form['#node']) && (oa_notifications_is_notification_type($form['#node']))) {
    $form['oa_notifications'] = array(
      '#type' => 'fieldset',
      '#title' => t('Notifications'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#tree' => TRUE,
    );
    oa_notifications_form_fields($form['oa_notifications'], $form_state, $form['#node']);
  }
}

/**
 * Return the listing of users to be notified for the provided Node.
 *
 * @param $node
 */
function oa_notifications_ajax_details($node) {
  $bucket = oa_notifications_get_notifications($node);

  $render = array();
  foreach ($bucket as $uid => $user) {
    if (node_access('view', $node, $user)) {
      $render[$uid] = array(
        'name' => $user->realname,
        'mail' => $user->mail,
      );
    }
  }

  echo theme('oa_notifications_details', array('users' => $render));
}