<?php

/**
 * Implements hook_ctools_plugin_directory
 */
function oa_notifications_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_theme().
 */
function oa_notifications_theme() {
  return array(
    'oa_notifications_view' => array(
      'template' => 'oa-notifications-view',
      'variables' => array(
        'organization' => array(),
        'team' => array(),
        'user' => array(),
      ),
      'path' => drupal_get_path('module', 'oa_notifications') . '/templates',
    ),
  );
}


/**
 * Some utility functions...
 */

/**
 * Get all Organizations
 */
function oa_notifications_get_orgs() {
  $query = db_select('node', 'n');
  $query->fields('n', array('nid', 'title'))
      ->condition('n.type', OA_ORG_TYPE)
      ->addTag('node_access');
  return $query->execute()->fetchAllAssoc('nid');
}

/**
 * Get the listing of teams that are in the specified group, or the current
 * group is no group is specified.
 *
 * @param int $gid
 *    The Group ID
 */
function oa_notifications_get_teams_for_group($gid = NULL) {
  if (!isset($gid)) {
    $gid = $_SESSION[OG_SESSION_CONTEXT_ID];
  }
  $query = db_select('node', 'n');
  $query->rightJoin('og_membership', 'og', 'n.nid = og.etid');
  $query->fields('n', array('nid', 'title'))
      ->condition('n.type', OA_TEAM_TYPE)
      ->condition('og.entity_type', 'node')
      ->condition('og.field_name', OA_GROUP_FIELD)
      ->condition('og.gid', $gid)
      ->addTag('node_access');
  return $query->execute()->fetchAllAssoc('nid');
}

/**
 * Get the listing of user with that are in the specified group, or the current
 * group if no group is specified that also have access to the provided node.
 *
 * @TODO: Consider the case where user.name is the not name to be used.
 *
 * @param int $gid
 *    The Group ID
 */
function oa_notifications_get_users_for_node($node, $gid = NULL) {
  if (!isset($gid)) {
    $gid = $_SESSION[OG_SESSION_CONTEXT_ID];
  }
  $query = db_select('users', 'u');
  $query->rightJoin('og_membership', 'og', 'u.uid = og.etid');
  $query->fields('u', array('uid', 'name'))
      ->condition('og.entity_type', 'user')
      ->condition('og.gid', $gid);

  $results = $query->execute()->fetchAllAssoc('uid');

  // @TODO: This won't scale. We need users that have access to the given node
  // which is controlled by node_access grants, etc.  Not easily queried.
  // The move to an autocomplete might make this potential performance problem disappear.
  $users = user_load_multiple(array_keys($results));
  foreach ($users as $uid => $user) {
    if (!node_access('view', $node, $user)) {
      unset($users[$uid]);
    }
  }
  return $users;
}

/**
 * Return all notifications for given source.  Optionally filtered by type.
 *
 * @param int $source_id
 *    The ID of the source (typically a nid)
 * @param string $source_type
 *    The entity type of the source (defaults to 'node')
 * @params string $target_type
 *    An optional parameter that allows to filter the notification based on target type (organization, team, user)
 * @return
 *    Returns an associative array of notifications first keyed by target type,
 *    then beneath that keyed by the target_id
 */
function oa_notifications_load_multiple($source_id, $source_type = 'node', $target_type = NULL) {
  $query = db_select('oa_notifications', 'n')
    ->fields('n')
    ->condition('n.source_id', $source_id)
    ->condition('n.$source_type', $source_type);

  if (isset($target_type)) {
    $query->condition('n.target_type', $target_type);
  }

  $notifications = array();
  $results = $query->execute()->fetchAllAssoc('notification_id');

  foreach ($results as $id => $row) {
    $notifications[$row->target_type][$row->target_id] = $row;
  }

  return $notifications;
}

/**
 * Save a collection of Notifications for a particular source item.
 *
 * @param int $source_id
 *    The ID of the source (typically a nid)
 * @param string $source_type
 *    The entity type of the source (defaults to 'node')
 * @param array $notifications
 *    A collection of Notification object for this source
 */
function oa_notifications_save_for_source($source_id, $source_type, $notifications) {
  db_delete('oa_notifications')
    ->condition('source_id', $source_id)
    ->condition('source_type', $source_type)
    ->execute();

  foreach ($notifications as $n) {
    drupal_write_record('oa_notifications', $n);
  }
}

/**
 * Implements hook_node_delete().
 *
 * Cleanup the notifications for teams and organizations as they are removed.
 *
 * @param $node
 *    The Node being deleted
 */
function oa_notifications_node_delete($node) {
  if ($node->type == 'oa_team') {
    $target_type = 'team';
  }
  else if ($node->type == 'oa_organization') {
    $target_type = 'organization';
  }

  if (isset($target_type)) {
    oa_notifications_delete_for_target($node->nid, $target_type);
  }
}

/**
 * Delete notifications for a target
 *
 * @param int $id
 *    The target id (e.g. node id)
 * @param string $type
 *    The target type (e.g. 'organization', 'team')
 */
function oa_notifications_delete_for_target($id, $type)
{
  db_delete('oa_notifications')
    ->condition('target_id', $id)
    ->condition('target_type', $type)
    ->execute();
}

